### ISSUE TITLE
Charts Appear in Spiky Chests

### ISSUE THREAD

**Issue by Crain-32** [SuperDude88/TWWHD-Randomizer#42]
```yaml
program_version: f41a879-dirty
file_version: 1.0
gameBaseDir: ""
outputDir: ""
seed: "FriendlyTWWHDRRace"
repack_for_console: false
consoleOutputDir: ""
progression_dungeons: Standard
progression_great_fairies: true
progression_puzzle_secret_caves: true
progression_combat_secret_caves: false
progression_short_sidequests: false
progression_long_sidequests: false
progression_spoils_trading: false
progression_minigames: false
progression_free_gifts: true
progression_mail: true
progression_platforms_rafts: false
progression_submarines: false
progression_eye_reef_chests: false
progression_big_octos_gunboats: false
progression_triforce_charts: false
progression_treasure_charts: false
progression_expensive_purchases: true
progression_misc: true
progression_tingle_chests: true
progression_battlesquid: false
progression_savage_labyrinth: false
progression_island_puzzles: true
progression_obscure: false
randomize_charts: false
randomize_starting_island: false
randomize_dungeon_entrances: false
randomize_boss_entrances: false
randomize_cave_entrances: false
randomize_door_entrances: false
randomize_misc_entrances: false
mix_dungeons: false
mix_bosses: false
mix_caves: false
mix_doors: false
mix_misc: false
decouple_entrances: false
ho_ho_hints: false
korl_hints: true
clearer_hints: true
use_always_hints: false
path_hints: 1
barren_hints: 2
item_hints: 2
location_hints: 0
instant_text_boxes: true
reveal_full_sea_chart: true
num_starting_triforce_shards: 0
add_shortcut_warps_between_dungeons: false
skip_rematch_bosses: true
invert_sea_compass_x_axis: false
num_required_dungeons: 0
damage_multiplier: 2.000000
chest_type_matches_contents: true
player_in_casual_clothes: false
starting_pohs: 0
starting_hcs: 0
starting_joy_pendants: 0
starting_skull_necklaces: 0
starting_boko_baba_seeds: 0
starting_golden_feathers: 0
starting_knights_crests: 0
starting_red_chu_jellys: 0
starting_green_chu_jellys: 0
starting_blue_chu_jellys: 0
remove_music: false
do_not_generate_spoiler_log: false
start_with_random_item: true
plandomizer: false
plandomizerFile: ""
sword_mode: Start With Sword
pig_color: RANDOM
dungeon_small_keys: Own Dungeon
dungeon_big_keys: Own Dungeon
dungeon_maps_compasses: Own Dungeon
target_type: Hold
camera: Standard
first_person_camera: Standard
gyroscope: On
ui_display: On
starting_gear:
  - Progressive Shield
  - Ballad of Gales
  - Song of Passing
  - Progressive Magic Meter
  - Progressive Sail
custom_colors:
  Belt: 633008
  Boots: 944908
  Pants: FFFFFF
  Belt Buckle: FFEF10
  Undershirt: ADE342
  Sclera: FFFFFF
  Tunic: 5AB24A
  Eyes: 10514A
  Mouth: F74963
  Skin: F7DB9C
  Hair: FFEF10
```
Played with this on the `wuhb` Linked in the `#updates` Channel. Charts were appearing in Spiky Chests, even though CTMC was enabled. Horseshoe is an example.
