### ISSUE TITLE
Permalinks should work

### ISSUE THREAD

**Issue by Crain-32** [SuperDude88/TWWHD-Randomizer#49]
Plugging this Permalink into the Desktop EXE doesn't work as expected.
YmZiAEZyaWVuZEhEUmFjZUFnYWluABoMiAECAgIGABR4AgIAqud5AAAIAgAAAAAAAAAAADnmAgA=

Should output the following config.yaml
```yml
program_version: bfbcfef
file_version: 1.0
gameBaseDir: ""
outputDir: ""
seed: FriendHDRaceAgain
repack_for_console: false
consoleOutputDir: ""
progression_dungeons: Race Mode
progression_great_fairies: true
progression_puzzle_secret_caves: true
progression_combat_secret_caves: false
progression_short_sidequests: false
progression_long_sidequests: false
progression_spoils_trading: false
progression_minigames: false
progression_free_gifts: true
progression_mail: true
progression_platforms_rafts: false
progression_submarines: false
progression_eye_reef_chests: false
progression_big_octos_gunboats: false
progression_triforce_charts: false
progression_treasure_charts: false
progression_expensive_purchases: false
progression_misc: true
progression_tingle_chests: false
progression_battlesquid: false
progression_savage_labyrinth: false
progression_island_puzzles: true
progression_obscure: true
randomize_charts: false
randomize_starting_island: false
randomize_dungeon_entrances: false
randomize_boss_entrances: false
randomize_cave_entrances: false
randomize_door_entrances: false
randomize_misc_entrances: false
mix_dungeons: false
mix_bosses: false
mix_caves: false
mix_doors: false
mix_misc: false
decouple_entrances: false
ho_ho_hints: false
korl_hints: true
clearer_hints: true
use_always_hints: false
path_hints: 3
barren_hints: 4
item_hints: 1
location_hints: 7
instant_text_boxes: true
reveal_full_sea_chart: true
num_starting_triforce_shards: 0
add_shortcut_warps_between_dungeons: true
skip_rematch_bosses: true
invert_sea_compass_x_axis: false
num_required_dungeons: 3
damage_multiplier: 2.000000
chest_type_matches_contents: true
player_in_casual_clothes: false
starting_pohs: 0
starting_hcs: 0
starting_joy_pendants: 0
starting_skull_necklaces: 0
starting_boko_baba_seeds: 0
starting_golden_feathers: 0
starting_knights_crests: 0
starting_red_chu_jellys: 0
starting_green_chu_jellys: 0
starting_blue_chu_jellys: 0
remove_music: false
do_not_generate_spoiler_log: false
start_with_random_item: true
plandomizer: false
plandomizerFile: ""
sword_mode: Start With Sword
pig_color: RANDOM
dungeon_small_keys: Own Dungeon
dungeon_big_keys: Own Dungeon
dungeon_maps_compasses: Own Dungeon
target_type: Hold
camera: Reverse Left/Right
first_person_camera: Standard
gyroscope: On
ui_display: On
starting_gear:
  - Ballad of Gales
  - Dragon Roost Cavern Compass
  - Dragon Roost Cavern Dungeon Map
  - Earth God's Lyric
  - Earth Temple Big Key
  - Earth Temple Compass
  - Forbidden Woods Big Key
  - Forbidden Woods Compass
  - Forsaken Fortress Compass
  - Forsaken Fortress Dungeon Map
  - Progressive Sail
  - Progressive Shield
  - Song of Passing
  - Telescope
  - Tower of the Gods Compass
  - Tower of the Gods Dungeon Map
  - Wind God's Aria
  - Wind Temple Compass
  - Wind Temple Dungeon Map
custom_colors:
  Belt Buckle: FFEF10
  Belt: 633008
  Undershirt: ADE342
  Pants: FFFFFF
  Sclera: FFFFFF
  Eyes: 10514A
  Boots: 944908
  Mouth: F74963
  Skin: F7DB9C
  Tunic: 5AB24A
  Hair: 73592F
  ```
